#!/bin/sh

set -eu

namespace="mutter-16/stacking mutter-16/thread.test"

if [ -z "${HOME-}" ] || ! [ -w "${HOME}" ]; then
    export HOME="${AUTOPKGTEST_TMP}"
fi

cd "$AUTOPKGTEST_TMP"

# Intentionally word-splitting $namespace:
# shellcheck disable=SC2086
tests="$(ginsttest-runner -l $namespace)"

if [ -z "$tests" ]; then
    echo "Error: no installed-tests found matching $namespace" >&2
    exit 1
fi

# copied from .gitlab-ci.yml
# needed by xwayland
mkdir -p -m 1777 /tmp/.X11-unix

e=0
# shellcheck disable=SC2086
ginsttest-runner \
    --log-directory "$AUTOPKGTEST_ARTIFACTS" \
    --tap \
    $namespace
